FROM python:3.7-alpine
LABEL maintainer="MF Tech"

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /requirements.txt
# install depencies but not caching them to keep the container as clean as possible
RUN apk add --update --no-cache postgresql-client
RUN apk add --update --no-cache --virtual .temp-build-deps \
      gcc libc-dev linux-headers postgresql-dev
RUN pip install -r /requirements.txt
RUN apk del .temp-build-deps

# creates a directory on the docker image
RUN mkdir /app
# sets the directory as root
WORKDIR /app
# copies the local app directory to the docker image
COPY ./app /app

# creates a user who can only runs stuff on the docker image
RUN adduser -D user
USER user